# Operating on Data in Pandas

## Ufuncs: Index Preservation

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(42)
ser = pd.Series(np.random.randint(1, 10, 4))
ser

0    7
1    4
2    8
3    5
dtype: int64

In [5]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D']
                  )
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.exp(ser)

0    1096.633158
1      54.598150
2    2980.957987
3     148.413159
dtype: float64

In [7]:
np.sin(df * np.pi/4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## Ufuncs: Index Alignment

### Index Alignment in Series

In [12]:
area = pd.Series({
            'Alaska': 1723337, 
            'Texas': 695662,
            'California': 423967
        }, 
        name='area')

population = pd.Series({
                'California': 39538223, 
                'Texas': 29145505,
                'Florida': 21538187
            }, 
            name='population')
print('Area:', area)
print('----------------')
print('Population:', population)

Area: Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64
----------------
Population: California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

In [13]:
population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [14]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='str')

In [16]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print(A)
print(B)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64

In [18]:
addition = A + B
addition

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [19]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [21]:
C = pd.DataFrame(np.random.randint(1, 20, (2, 2)), columns=['A', 'B'])
C

   A   B
0  2  12
1  6   2

In [23]:
D = pd.DataFrame(np.random.randint(0, 10, (3, 3)), columns=['A', 'B', 'C'])
D

   A  B  C
0  3  8  2
1  4  2  6
2  4  8  6

In [26]:
addition_1 = D + C
addition_1

      A     B   C
0   5.0  20.0 NaN
1  10.0   4.0 NaN
2   NaN   NaN NaN

In [27]:
C.add(D, fill_value=A.values.mean())

      A     B     C
0   5.0  20.0   6.0
1  10.0   4.0  10.0
2   8.0  12.0  10.0

## Ufuncs: Operations Between DataFrame and Series

In [28]:
np.random.seed(42)
A = np.random.randint(10, size=(3, 4))
A

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [30]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0,  6, -5,  2],
       [ 1,  1, -4,  3]])

In [31]:
df = pd.DataFrame(A, columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [32]:
df.subtract(df['A'], axis=0)

   A  B  C  D
0  0 -3  1 -2
1  0  3 -4  0
2  0 -3 -4  0