# Operating on Data in Pandas

## Ufuncs: Index Preservation

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(42)
ser = pd.Series(np.random.randint(1, 10, 4))
ser

0    7
1    4
2    8
3    5
dtype: int64

In [5]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D']
                  )
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.exp(ser)

0    1096.633158
1      54.598150
2    2980.957987
3     148.413159
dtype: float64

In [7]:
np.sin(df * np.pi/4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## Ufuncs: Index Alignment

### Index Alignment in Series

In [12]:
area = pd.Series({
            'Alaska': 1723337, 
            'Texas': 695662,
            'California': 423967
        }, 
        name='area')

population = pd.Series({
                'California': 39538223, 
                'Texas': 29145505,
                'Florida': 21538187
            }, 
            name='population')
print('Area:', area)
print('----------------')
print('Population:', population)

Area: Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64
----------------
Population: California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

In [13]:
population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64