## Load and Explore the Dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/Superstore (1).csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1.0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2.0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3.0,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4.0,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5.0,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9800.000000,9789.000000,9800.000000,9994.000000,9994.000000,9994.000000
mean,4900.500000,55273.322403,230.769059,3.789574,0.156203,28.656896
std,2829.160653,32041.223413,626.651875,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2450.750000,23223.000000,17.248000,2.000000,0.000000,1.728750
50%,4900.500000,58103.000000,54.490000,3.000000,0.200000,8.666500
75%,7350.250000,90008.000000,210.605000,5.000000,0.200000,29.364000
max,9800.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [6]:
# check for duplicates
duplicates = df.duplicated().sum()
duplicates

np.int64(2)

### How much total sales?

In [8]:
df['Sales'].sum()

np.float64(2261536.7827)

### Which Category generates the most sales?

In [14]:
max_category = df.groupby('Category')['Sales'].sum().idxmax()
print(f"The category that generates the most sales is: {max_category}")

The category that generates the most sales is: Technology

In [ ]:
# sort the categories by sales
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

### Sales And Profit by Category

In [16]:
sap_category = df.groupby('Category')[['Sales', 'Profit']].sum()
sap_category

                       Sales       Profit
Category
Furniture        728658.5757   16921.6842
Office Supplies  705422.3340  118956.3861
Technology       827455.8730  143100.5405

In [23]:
# using a pivot table
sap_category_pt = df.pivot_table(index='Category', values=['Sales', 'Profit'], aggfunc='sum')
sap_category_pt

                      Profit        Sales
Category
Furniture         16921.6842  728658.5757
Office Supplies  118956.3861  705422.3340
Technology       143100.5405  827455.8730

### Sales and Profit by Region

In [ ]:
# using pivot tables
sap_region_pt = df.pivot_table(index='Region', values=['Sales', 'Profit'], aggfunc='sum')
sap_region_pt

              Profit        Sales
Region
Central   37866.0619  492646.9132
East      89512.0804  669518.7260
South     46243.2616  389151.4590
West     105357.2069  710219.6845

In [22]:
# using groupby
sap_region_gb = df.groupby('Region')[['Sales', 'Profit']].sum()
sap_region_gb

               Sales       Profit
Region
Central  492646.9132   37866.0619
East     669518.7260   89512.0804
South    389151.4590   46243.2616
West     710219.6845  105357.2069