# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [3]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

products_over_10 = len(chipo[chipo['item_price'] > 10])
products_over_10

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [4]:
price_df = chipo[['item_name', 'item_price']]
price_df_unique = price_df.drop_duplicates()
price_df_unique

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4237                    Chips and Guacamole        8.50
4354                       Steak Soft Tacos       18.50
4489                    Chips and Guacamole       17.80
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [7]:
sorted_items = price_df_unique.sort_values('item_name')
sorted_items.head(15)

                  item_name  item_price
298       6 Pack Soft Drink        6.49
3389      6 Pack Soft Drink       12.98
39            Barbacoa Bowl       11.75
95            Barbacoa Bowl        9.25
115           Barbacoa Bowl        8.99
471           Barbacoa Bowl       11.48
3195          Barbacoa Bowl        8.69
4510          Barbacoa Bowl       11.49
21         Barbacoa Burrito        8.99
81         Barbacoa Burrito        9.25
130        Barbacoa Burrito       11.75
1648       Barbacoa Burrito       11.08
3156       Barbacoa Burrito        8.69
3276       Barbacoa Burrito       11.48
168   Barbacoa Crispy Tacos       11.75

### Step 7. What was the quantity of the most expensive item ordered?

In [8]:
most_expensive_idx = chipo['item_price'].idxmax()
most_expensive_row = chipo.loc[most_expensive_idx]
quantity = most_expensive_row['quantity']
quantity

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [9]:
veggie_count = chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()
veggie_count

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [10]:
canned_soda_multi = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
count = len(canned_soda_multi)
count

20